
"use client";

import { motion } from "framer-motion";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import Link from "next/link";

export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto py-20 px-6 text-left selection:bg-primary/20">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="space-y-12"
      >
        {/* Header Section */}
        <div className="space-y-8">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <h1 className="text-4xl sm:text-6xl font-black tracking-tighter text-white font-headline">
              Disclaimer
            </h1>
            <Badge variant="outline" className="w-fit font-black text-[9px] uppercase tracking-widest bg-primary/5 text-primary border-primary/10 px-4 py-1.5 rounded-full">
              Statutory notice
            </Badge>
          </div>
          
          <div className="space-y-2 text-sm sm:text-base font-bold text-white/60 uppercase tracking-widest">
            <p>Effective date: <span className="text-primary">04-02-2023</span></p>
            <p>Last updated: <span className="text-primary">09-02-2026</span></p>
          </div>

          <div className="space-y-6 text-lg text-white/80 font-medium leading-relaxed max-w-3xl">
            <p>
              Nyaya Sahayak is an AI-powered legal information platform designed to help users understand Indian laws and legal processes. Please read this Disclaimer carefully before using the Platform.
            </p>
            <p>
              By accessing or using Nyaya Sahayak (nyayasahayak.in), you acknowledge and agree to the terms of this Disclaimer.
            </p>
          </div>
        </div>

        <Separator className="bg-white/10" />

        {/* Content Sections */}
        <div className="space-y-16 pt-4">
          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">1. General information only – Not legal advice</h2>
            <div className="space-y-4 text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              <p>Nyaya Sahayak provides general legal information based on Indian laws for educational and informational purposes only.</p>
              <ul className="list-disc pl-5 space-y-3">
                <li>The information generated by the AI chatbot does not constitute legal advice.</li>
                <li>The content is not tailored to your specific facts, circumstances, or jurisdiction.</li>
                <li>You should not act or refrain from acting based solely on information obtained from Nyaya Sahayak.</li>
                <li>For advice specific to your legal issue, you must consult a qualified and licensed advocate.</li>
              </ul>
            </div>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">2. No lawyer–client relationship</h2>
            <div className="space-y-4 text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              <p>Use of Nyaya Sahayak does not create any lawyer–client relationship between you and:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Nyaya Sahayak</li>
                <li>Its founders, developers, contributors, or affiliates</li>
                <li>Any lawyers, legal professionals, or institutions referenced on the Platform</li>
              </ul>
              <p>Nyaya Sahayak is not a law firm and does not offer professional legal representation.</p>
            </div>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">3. AI-generated content & limitations</h2>
            <div className="space-y-4 text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              <p>Nyaya Sahayak uses artificial intelligence to generate responses. As a result:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Responses may be incomplete, outdated, inaccurate, or oversimplified.</li>
                <li>Laws, rules, procedures, and interpretations may change over time.</li>
                <li>AI systems may occasionally produce incorrect or misleading outputs.</li>
              </ul>
              <p>While we aim to provide helpful and relevant information, no guarantees are made regarding the accuracy, completeness, or reliability of AI-generated content.</p>
            </div>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">4. Jurisdictional scope</h2>
            <p className="text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              Nyaya Sahayak provides information only with respect to Indian law. It does not provide legal information relating to foreign laws or international jurisdictions. Legal rights and procedures may vary by state within India. Users are responsible for verifying applicability to their specific jurisdiction.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">5. Documents, uploads & analysis</h2>
            <div className="space-y-4 text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              <p>If you upload documents to Nyaya Sahayak:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Any analysis, summary, or response is informational only.</li>
                <li>Document review does not replace professional legal scrutiny.</li>
                <li>Nyaya Sahayak does not verify authenticity, completeness, or legal sufficiency of uploaded documents.</li>
              </ul>
              <p>You should always have important documents reviewed by a qualified legal professional.</p>
            </div>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">6. Paid services clarification</h2>
            <div className="space-y-4 text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              <p>Nyaya Sahayak may offer paid plans that provide access to additional features, higher usage limits, or enhanced tools.</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Payment does not entitle you to legal consultation or personalized legal advice.</li>
                <li>Paid services do not create any lawyer–client relationship.</li>
                <li>Fees are charged for platform access and features only.</li>
              </ul>
            </div>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">7. No warranties</h2>
            <p className="text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              Nyaya Sahayak is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. We make no warranties, express or implied, including but not limited to: accuracy or reliability of information, fitness for a particular purpose, or continuous and error-free operation.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">8. Limitation of liability</h2>
            <div className="space-y-4 text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              <p>To the maximum extent permitted by law, Nyaya Sahayak, its owners, developers, affiliates, and partners shall not be liable for any loss, damage, or harm arising from:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Use of or reliance on information provided by the Platform.</li>
                <li>Errors, omissions, or inaccuracies in AI-generated content.</li>
                <li>Decisions or actions taken based on Platform outputs.</li>
              </ul>
              <p className="font-bold text-primary italic">Use of Nyaya Sahayak is entirely at your own risk.</p>
            </div>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">9. Third-party references & links</h2>
            <p className="text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              Nyaya Sahayak may reference or link to third-party websites, articles, or resources for informational purposes. Such references do not constitute endorsement. Nyaya Sahayak is not responsible for third-party content, accuracy, or practices. Accessing third-party resources is at your own discretion and risk.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">10. Privacy & data handling</h2>
            <p className="text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              All personal data collected through Nyaya Sahayak is handled in accordance with our Privacy Policy. For details on data collection, usage, storage, and protection, please review the Privacy Policy available on our website.
            </p>
          </section>

          <section className="space-y-6 pb-10">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">11. Acceptance of disclaimer</h2>
            <div className="p-8 rounded-[2rem] bg-white/5 border border-white/10 space-y-4">
              <p className="text-white/80 font-medium leading-relaxed">
                By using Nyaya Sahayak, you confirm that you have read, understood, and agreed to this Disclaimer, along with our Terms of Service and Privacy Policy. If you do not agree with any part of this Disclaimer, you must discontinue use of the Platform immediately.
              </p>
              <div className="flex flex-col gap-2 pt-4">
                <a href="mailto:nyayasahayakhelp@gmail.com" className="text-2xl font-black text-primary hover:underline transition-all">nyayasahayakhelp@gmail.com</a>
                <p className="text-[10px] font-black text-white/20 uppercase tracking-[0.4em]">Nyaya Sahayak // Registry node</p>
              </div>
            </div>
          </section>
        </div>
      </motion.div>
    </div>
  );
}
