"use client";

import { PageHeader } from "@/components/page-header";
import { Card, CardContent } from "@/components/ui/card";
import { AlertCircle, Gavel, Scale, Info } from "lucide-react";

export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-12 text-left">
      <PageHeader
        title="Legal Disclaimer"
        description="Mandatory institutional disclosure regarding AI intelligence and human advocacy."
      />

      <div className="grid gap-6 sm:grid-cols-2">
        <Card className="border-destructive/20 bg-destructive/5 rounded-2xl">
          <CardContent className="p-6 space-y-3">
            <div className="flex items-center gap-2 text-destructive">
              <Gavel className="h-5 w-5" />
              <h3 className="font-black uppercase tracking-tighter text-sm">Non-Official Node</h3>
            </div>
            <p className="text-xs font-bold leading-relaxed text-destructive/80">
              The AI Nyaya Mitra Assistant is NOT a law firm or a government entity. We do not provide official legal advice, only AI-driven forensic intelligence.
            </p>
          </CardContent>
        </Card>
        <Card className="border-amber-500/20 bg-amber-500/5 rounded-2xl">
          <CardContent className="p-6 space-y-3">
            <div className="flex items-center gap-2 text-amber-600">
              <Scale className="h-5 w-5" />
              <h3 className="font-black uppercase tracking-tighter text-sm">Human Review Mandate</h3>
            </div>
            <p className="text-xs font-bold leading-relaxed text-amber-600/80">
              All documents generated by AI nodes MUST be reviewed and finalized by a qualified human advocate before filing in any official court of law.
            </p>
          </CardContent>
        </Card>
      </div>

      <Card className="border-primary/5 shadow-2xl rounded-2xl bg-card overflow-hidden">
        <CardContent className="p-8 sm:p-12 space-y-6">
          <div className="flex items-center gap-3 text-primary mb-4">
            <Info className="h-6 w-6" />
            <h2 className="text-2xl font-black tracking-tight leading-none">Full Disclosure</h2>
          </div>
          <div className="space-y-6 text-sm text-muted-foreground font-medium leading-relaxed prose dark:prose-invert max-w-none">
            <p>
              By utilizing any dashboard modules, you acknowledge that the system operates on probabilistic AI nodes. While we strive for 100% forensic accuracy, discrepancies in relevant laws or sections may occur. Nyaya Sahayak institutional nodes are not liable for any legal outcomes resulting from reliance on AI-generated data.
            </p>
            <p>
              We highly recommend connecting with our <span className="font-bold text-primary italic">Verified Advocate Registry</span> for personalized consultations. Only a human professional can provide the nuanced strategy required for complex litigation.
            </p>
            <p className="pt-4 border-t border-primary/5 text-[10px] font-black uppercase tracking-widest">
              Institutional ID: NS-NODE-001 // SECURE REGISTRY CLEARANCE REQUIRED
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
