
"use client";

import { motion } from "framer-motion";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export default function DisclaimerDashboardPage() {
  return (
    <div className="max-w-4xl mx-auto py-10 pb-32 px-4 text-left selection:bg-primary/20">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="space-y-12"
      >
        {/* Navigation Ingress */}
        <div className="flex items-center justify-between border-b border-white/5 pb-6">
          <Button variant="ghost" size="sm" className="rounded-xl font-bold hover:bg-white/5 group h-10 px-6 border border-white/5 text-white text-[10px] uppercase tracking-widest" asChild>
            <Link href="/dashboard">
              <ArrowLeft className="mr-2 h-3.5 w-3.5 transition-transform group-hover:-translate-x-1" /> Back to dashboard
            </Link>
          </Button>
        </div>

        {/* Header Section */}
        <div className="space-y-8 pt-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <h1 className="text-4xl sm:text-6xl font-black tracking-tighter text-white font-headline">
              Disclaimer
            </h1>
            <Badge variant="outline" className="w-fit font-black text-[9px] uppercase tracking-widest bg-primary/5 text-primary border-primary/10 px-4 py-1.5 rounded-full">
              Institutional notice
            </Badge>
          </div>
          
          <div className="space-y-2 text-sm sm:text-base font-bold text-white/60 uppercase tracking-widest">
            <p>Effective date: <span className="text-primary">12/04/2026</span></p>
            <p>Last updated: <span className="text-primary">12/04/2026</span></p>
          </div>

          <div className="space-y-6 text-lg text-white/80 font-medium leading-relaxed max-w-3xl">
            <p>
              Nyaya Sahayak is an AI-powered legal information platform designed to help users understand Indian laws and legal processes. Please read this Disclaimer carefully before using the Platform.
            </p>
            <p>
              By accessing or using Nyaya Sahayak (nyayasahayak.in), you acknowledge and agree to the terms of this Disclaimer.
            </p>
          </div>
        </div>

        <Separator className="bg-white/10" />

        {/* Content Sections */}
        <div className="space-y-16 pt-4">
          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">1. General information only – Not legal advice</h2>
            <div className="space-y-4 text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              <p>Nyaya Sahayak provides general legal information based on Indian laws for educational and informational purposes only.</p>
              <ul className="list-disc pl-5 space-y-3">
                <li>The information generated by the AI chatbot does not constitute legal advice.</li>
                <li>The content is not tailored to your specific facts, circumstances, or jurisdiction.</li>
                <li>You should not act or refrain from acting based solely on information obtained from Nyaya Sahayak.</li>
                <li>For advice specific to your legal issue, you must consult a qualified and licensed advocate.</li>
              </ul>
            </div>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">2. No lawyer–client relationship</h2>
            <div className="space-y-4 text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              <p>Use of Nyaya Sahayak does not create any lawyer–client relationship between you and Nyaya Sahayak, its founders, or contributors.</p>
              <p>Nyaya Sahayak is not a law firm and does not offer professional legal representation.</p>
            </div>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">3. AI-generated content & limitations</h2>
            <div className="space-y-4 text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              <p>Nyaya Sahayak uses artificial intelligence to generate responses. As a result:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Responses may be incomplete, outdated, inaccurate, or oversimplified.</li>
                <li>Laws, rules, procedures, and interpretations may change over time.</li>
                <li>AI systems may occasionally produce incorrect or misleading outputs.</li>
              </ul>
              <p>Accuracy verification rests with the user.</p>
            </div>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">4. Jurisdictional scope</h2>
            <p className="text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              Nyaya Sahayak provides information only with respect to Indian law. Users are responsible for verifying applicability to their specific state jurisdiction.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">5. Documents, uploads & analysis</h2>
            <div className="space-y-4 text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              <p>Any analysis or response provided for uploaded documents is informational only and does not replace professional legal scrutiny.</p>
            </div>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">6. Paid services clarification</h2>
            <p className="text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              Fees are charged for platform access and AI features only. Payment does not create an attorney-client relationship.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">7. No warranties</h2>
            <p className="text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              Nyaya Sahayak is provided on an &ldquo;as is&rdquo; basis without warranties of accuracy or reliability.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">8. Limitation of liability</h2>
            <p className="text-white/60 font-medium text-sm sm:text-base leading-relaxed">
              To the maximum extent permitted by law, Nyaya Sahayak shall not be liable for any loss arising from use of or reliance on information provided by the Platform.
            </p>
          </section>

          <section className="space-y-6 pb-10">
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">11. Acceptance of disclaimer</h2>
            <div className="p-8 rounded-[2rem] bg-white/5 border border-white/10 space-y-4">
              <p className="text-white/80 font-medium leading-relaxed">
                By utilizing dashboard modules on nyayasahayak.in, you acknowledge that the system operates on probabilistic AI. Our mission is to democratize legal information, not replace human strategy required for litigation.
              </p>
              <div className="flex flex-col gap-2 pt-4">
                <a href="mailto:nyayasahayakhelp@gmail.com" className="text-2xl font-black text-primary hover:underline transition-all">nyayasahayakhelp@gmail.com</a>
                <p className="text-[10px] font-black text-white/20 uppercase tracking-[0.4em]">Nyaya Sahayak // Disclaimer Protocol</p>
              </div>
            </div>
          </section>
        </div>
      </motion.div>
    </div>
  );
}
